[package]
authors = ["Will Ross <paxswill@paxswill.com>"]
categories = ["embedded", "hardware-support"]
description = "Library for interfacing with Melexis MLX9064* thermal cameras"
edition = "2021"
keywords = ["embedded-hal", "thermal-camera", "thermopile", "mlx90640", "mlx90641"]
license = "Apache-2.0"
name = "mlx9064x"
version = "0.3.0"
readme = "ReadMe.md"
repository = "https://github.com/paxswill/mlx9064x-rs"
autoexamples = false

[dependencies]
# anyhow is only required for examples
anyhow = { version = "1.0", optional = true }
tokio = { version = "1.0", features = ["rt-multi-thread", "time", "macros"], optional = true }
arrayvec = { version = "0.7", default-features = false }
bitvec = { version = "1", default-features = false }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
num_enum = { version = "0.5", default-features = false }
num-traits = { version = "0.2", default-features = false }
paste = "1"

[dev-dependencies]
float-cmp = "0.9.0"
criterion = "0.3"

[dev-dependencies.mlx9064x-test-data]
path = "../mlx9064x-test-data"
version = "0.2.1"

[features]
default = ["std"]
examples = ["anyhow", "std"]
async-examples = ["tokio", "std"]
libm = ["num-traits/libm"]
std = ["arrayvec/std", "num-traits/std"]


[[example]]
name = "async_camera"
required-features = ["async-examples"]

[[bench]]
name = "raw_to_temperatures"
harness = false

[[bench]]
name = "load_calibration"
harness = false
